# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - "main"
      - "fix/*"
      - "feat/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test

      - name: Create docker image
        run: docker build . -t react-images

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{github.actor}} -p ${{ secrets.TOKEN }}
      - name: Determine tag version
        id: determine_tag_version
        run: echo "::set-output name=tag_version::$(echo ${{ github.head_ref }} | sed 's/[^[:alnum:]]//g' | tr '[:upper:]' '[:lower:]')"
      - name: Set image tag
        if: startsWith(github.head_ref, 'fix/')
        run: echo "::set-output name=image_tag::$(echo ${{ env.IMAGE_TAG }} | awk -F '.' '{printf \"%d.%d.%d\", $1, $2, $3+1}')"
        env:
          IMAGE_TAG: ${{ steps.determine_tag_version.outputs.tag_version }}.0.1
      - name: Set image tag
        if: startsWith(github.head_ref, 'feat/')
        run: echo "::set-output name=image_tag::$(echo ${{ env.IMAGE_TAG }} | awk -F '.' '{printf \"%d.%d.%d\", $1, $2+1, $3}')"
        env:
          IMAGE_TAG: ${{ steps.determine_tag_version.outputs.tag_version }}.1.0

      - name: Tag image
        run: docker tag react-images ghcr.io/sunnybenji/react-images:${{ steps.determine_tag_version.outputs.tag_version }}-${{ steps.build.outputs.job_id }}

      - name: Push image
        run: docker push ghcr.io/sunnybenji/react-images:${{ steps.determine_tag_version.outputs.tag_version }}-${{ steps.build.outputs.job_id }}
